name: blocknot.es tests

env:
  RUBY_VERSION: 2.7.3

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 6'

jobs:
  run-rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-cache-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-cache-

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Run specs
        run: bin/rspec --profile 10 --format progress
